//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Popyt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкеты.
    /// </summary>
    // *** Start programmer edit section *** (Анкеты CustomAttributes)

    // *** End programmer edit section *** (Анкеты CustomAttributes)
    [AutoAltered()]
    [Caption("Анкеты уволившихся работников")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АнкетыE", new string[] {
            "ДатаЗаполн as \'Дата заполнения\'",
            "ОтносКатСотр as \'Категория сотрудников\'",
            "КакойСтаж as \'Стаж\'",
            "ВозрастСотруд as \'Возраст сотрудника\'",
            "Коммент as \'Комментарии уволившегося сотрудника\'"})]
    [AssociatedDetailViewAttribute("АнкетыE", "ОценПричУвольн", "ОценПричУвольнE", false, "", "Оценки", true, new string[] {
            ""})]
    [View("АнкетыL", new string[] {
            "ДатаЗаполн as \'Дата заполн\'",
            "КакойСтаж as \'Какой стаж\'",
            "ВозрастСотруд as \'Возраст сотруд\'"})]
    public class Анкеты : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаполн;
        
        private IIS.Popyt.КатегСотруд fОтносКатСотр;
        
        private IIS.Popyt.Стаж fКакойСтаж;
        
        private IIS.Popyt.Возраст fВозрастСотруд;
        
        private string fКоммент;
        
        private IIS.Popyt.Специалист fСпециалист;
        
        private IIS.Popyt.DetailArrayOfОценПричУвольн fОценПричУвольн;
        
        // *** Start programmer edit section *** (Анкеты CustomMembers)

        // *** End programmer edit section *** (Анкеты CustomMembers)

        
        /// <summary>
        /// ВозрастСотруд.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ВозрастСотруд CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ВозрастСотруд CustomAttributes)
        public virtual IIS.Popyt.Возраст ВозрастСотруд
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Get start)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Get start)
                IIS.Popyt.Возраст result = this.fВозрастСотруд;
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Get end)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Set start)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Set start)
                this.fВозрастСотруд = value;
                // *** Start programmer edit section *** (Анкеты.ВозрастСотруд Set end)

                // *** End programmer edit section *** (Анкеты.ВозрастСотруд Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаполн.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ДатаЗаполн CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ДатаЗаполн CustomAttributes)
        public virtual System.DateTime ДатаЗаполн
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Get start)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Get start)
                System.DateTime result = this.fДатаЗаполн;
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Get end)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Set start)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Set start)
                this.fДатаЗаполн = value;
                // *** Start programmer edit section *** (Анкеты.ДатаЗаполн Set end)

                // *** End programmer edit section *** (Анкеты.ДатаЗаполн Set end)
            }
        }
        
        /// <summary>
        /// КакойСтаж.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.КакойСтаж CustomAttributes)

        // *** End programmer edit section *** (Анкеты.КакойСтаж CustomAttributes)
        public virtual IIS.Popyt.Стаж КакойСтаж
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Get start)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Get start)
                IIS.Popyt.Стаж result = this.fКакойСтаж;
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Get end)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Set start)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Set start)
                this.fКакойСтаж = value;
                // *** Start programmer edit section *** (Анкеты.КакойСтаж Set end)

                // *** End programmer edit section *** (Анкеты.КакойСтаж Set end)
            }
        }
        
        /// <summary>
        /// Коммент.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Коммент CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Коммент CustomAttributes)
        [StrLen(255)]
        public virtual string Коммент
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Коммент Get start)

                // *** End programmer edit section *** (Анкеты.Коммент Get start)
                string result = this.fКоммент;
                // *** Start programmer edit section *** (Анкеты.Коммент Get end)

                // *** End programmer edit section *** (Анкеты.Коммент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Коммент Set start)

                // *** End programmer edit section *** (Анкеты.Коммент Set start)
                this.fКоммент = value;
                // *** Start programmer edit section *** (Анкеты.Коммент Set end)

                // *** End programmer edit section *** (Анкеты.Коммент Set end)
            }
        }
        
        /// <summary>
        /// ОтносКатСотр.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ОтносКатСотр CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ОтносКатСотр CustomAttributes)
        public virtual IIS.Popyt.КатегСотруд ОтносКатСотр
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Get start)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Get start)
                IIS.Popyt.КатегСотруд result = this.fОтносКатСотр;
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Get end)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Set start)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Set start)
                this.fОтносКатСотр = value;
                // *** Start programmer edit section *** (Анкеты.ОтносКатСотр Set end)

                // *** End programmer edit section *** (Анкеты.ОтносКатСотр Set end)
            }
        }
        
        /// <summary>
        /// Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.Специалист CustomAttributes)

        // *** End programmer edit section *** (Анкеты.Специалист CustomAttributes)
        [PropertyStorage(new string[] {
                "Специалист"})]
        public virtual IIS.Popyt.Специалист Специалист
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.Специалист Get start)

                // *** End programmer edit section *** (Анкеты.Специалист Get start)
                IIS.Popyt.Специалист result = this.fСпециалист;
                // *** Start programmer edit section *** (Анкеты.Специалист Get end)

                // *** End programmer edit section *** (Анкеты.Специалист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.Специалист Set start)

                // *** End programmer edit section *** (Анкеты.Специалист Set start)
                this.fСпециалист = value;
                // *** Start programmer edit section *** (Анкеты.Специалист Set end)

                // *** End programmer edit section *** (Анкеты.Специалист Set end)
            }
        }
        
        /// <summary>
        /// Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (Анкеты.ОценПричУвольн CustomAttributes)

        // *** End programmer edit section *** (Анкеты.ОценПричУвольн CustomAttributes)
        public virtual IIS.Popyt.DetailArrayOfОценПричУвольн ОценПричУвольн
        {
            get
            {
                // *** Start programmer edit section *** (Анкеты.ОценПричУвольн Get start)

                // *** End programmer edit section *** (Анкеты.ОценПричУвольн Get start)
                if ((this.fОценПричУвольн == null))
                {
                    this.fОценПричУвольн = new IIS.Popyt.DetailArrayOfОценПричУвольн(this);
                }
                IIS.Popyt.DetailArrayOfОценПричУвольн result = this.fОценПричУвольн;
                // *** Start programmer edit section *** (Анкеты.ОценПричУвольн Get end)

                // *** End programmer edit section *** (Анкеты.ОценПричУвольн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкеты.ОценПричУвольн Set start)

                // *** End programmer edit section *** (Анкеты.ОценПричУвольн Set start)
                this.fОценПричУвольн = value;
                // *** Start programmer edit section *** (Анкеты.ОценПричУвольн Set end)

                // *** End programmer edit section *** (Анкеты.ОценПричУвольн Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АнкетыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыE", typeof(IIS.Popyt.Анкеты));
                }
            }
            
            /// <summary>
            /// "АнкетыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АнкетыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АнкетыL", typeof(IIS.Popyt.Анкеты));
                }
            }
        }
    }
}
