//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Popyt
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Возраст.
    /// </summary>
    // *** Start programmer edit section *** (Возраст CustomAttributes)

    // *** End programmer edit section *** (Возраст CustomAttributes)
    public enum Возраст
    {
        
        // *** Start programmer edit section *** (Возраст.До35л CustomAttributes)

        // *** End programmer edit section *** (Возраст.До35л CustomAttributes)
        До35л,
        
        // *** Start programmer edit section *** (Возраст.от55 CustomAttributes)

        // *** End programmer edit section *** (Возраст.от55 CustomAttributes)
        от55,
        
        // *** Start programmer edit section *** (Возраст.От35 CustomAttributes)

        // *** End programmer edit section *** (Возраст.От35 CustomAttributes)
        От35,
        
        // *** Start programmer edit section *** (Возраст.От45 CustomAttributes)

        // *** End programmer edit section *** (Возраст.От45 CustomAttributes)
        От45,
    }
}
