//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Popyt
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Категории сотрудников.
    /// </summary>
    // *** Start programmer edit section *** (КатегСотруд CustomAttributes)

    // *** End programmer edit section *** (КатегСотруд CustomAttributes)
    public enum КатегСотруд
    {
        
        // *** Start programmer edit section *** (КатегСотруд.Специалисты CustomAttributes)

        // *** End programmer edit section *** (КатегСотруд.Специалисты CustomAttributes)
        Специалисты,
        
        // *** Start programmer edit section *** (КатегСотруд.Рабочие CustomAttributes)

        // *** End programmer edit section *** (КатегСотруд.Рабочие CustomAttributes)
        Рабочие,
        
        // *** Start programmer edit section *** (КатегСотруд.Руководители CustomAttributes)

        // *** End programmer edit section *** (КатегСотруд.Руководители CustomAttributes)
        Руководители,
    }
}
