//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Popyt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оцен прич увольн.
    /// </summary>
    // *** Start programmer edit section *** (ОценПричУвольн CustomAttributes)

    // *** End programmer edit section *** (ОценПричУвольн CustomAttributes)
    [AutoAltered()]
    [Caption("Оценка причин увольнения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОценПричУвольнE", new string[] {
            "НеУдовл as \'1-5 (не удовлетворен)\'",
            "Удовл as \'6-10 (удовлетворен)\'"})]
    public class ОценПричУвольн : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Popyt.Факторы fНеУдовл;
        
        private IIS.Popyt.Факторы fУдовл;
        
        private IIS.Popyt.Анкеты fАнкеты;
        
        // *** Start programmer edit section *** (ОценПричУвольн CustomMembers)

        // *** End programmer edit section *** (ОценПричУвольн CustomMembers)

        
        /// <summary>
        /// НеУдовл.
        /// </summary>
        // *** Start programmer edit section *** (ОценПричУвольн.НеУдовл CustomAttributes)

        // *** End programmer edit section *** (ОценПричУвольн.НеУдовл CustomAttributes)
        public virtual IIS.Popyt.Факторы НеУдовл
        {
            get
            {
                // *** Start programmer edit section *** (ОценПричУвольн.НеУдовл Get start)

                // *** End programmer edit section *** (ОценПричУвольн.НеУдовл Get start)
                IIS.Popyt.Факторы result = this.fНеУдовл;
                // *** Start programmer edit section *** (ОценПричУвольн.НеУдовл Get end)

                // *** End programmer edit section *** (ОценПричУвольн.НеУдовл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценПричУвольн.НеУдовл Set start)

                // *** End programmer edit section *** (ОценПричУвольн.НеУдовл Set start)
                this.fНеУдовл = value;
                // *** Start programmer edit section *** (ОценПричУвольн.НеУдовл Set end)

                // *** End programmer edit section *** (ОценПричУвольн.НеУдовл Set end)
            }
        }
        
        /// <summary>
        /// Удовл.
        /// </summary>
        // *** Start programmer edit section *** (ОценПричУвольн.Удовл CustomAttributes)

        // *** End programmer edit section *** (ОценПричУвольн.Удовл CustomAttributes)
        public virtual IIS.Popyt.Факторы Удовл
        {
            get
            {
                // *** Start programmer edit section *** (ОценПричУвольн.Удовл Get start)

                // *** End programmer edit section *** (ОценПричУвольн.Удовл Get start)
                IIS.Popyt.Факторы result = this.fУдовл;
                // *** Start programmer edit section *** (ОценПричУвольн.Удовл Get end)

                // *** End programmer edit section *** (ОценПричУвольн.Удовл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценПричУвольн.Удовл Set start)

                // *** End programmer edit section *** (ОценПричУвольн.Удовл Set start)
                this.fУдовл = value;
                // *** Start programmer edit section *** (ОценПричУвольн.Удовл Set end)

                // *** End programmer edit section *** (ОценПричУвольн.Удовл Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Popyt.Анкеты.
        /// </summary>
        // *** Start programmer edit section *** (ОценПричУвольн.Анкеты CustomAttributes)

        // *** End programmer edit section *** (ОценПричУвольн.Анкеты CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Анкеты"})]
        public virtual IIS.Popyt.Анкеты Анкеты
        {
            get
            {
                // *** Start programmer edit section *** (ОценПричУвольн.Анкеты Get start)

                // *** End programmer edit section *** (ОценПричУвольн.Анкеты Get start)
                IIS.Popyt.Анкеты result = this.fАнкеты;
                // *** Start programmer edit section *** (ОценПричУвольн.Анкеты Get end)

                // *** End programmer edit section *** (ОценПричУвольн.Анкеты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОценПричУвольн.Анкеты Set start)

                // *** End programmer edit section *** (ОценПричУвольн.Анкеты Set start)
                this.fАнкеты = value;
                // *** Start programmer edit section *** (ОценПричУвольн.Анкеты Set end)

                // *** End programmer edit section *** (ОценПричУвольн.Анкеты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОценПричУвольнE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОценПричУвольнE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОценПричУвольнE", typeof(IIS.Popyt.ОценПричУвольн));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОценПричУвольн.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОценПричУвольн CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОценПричУвольн CustomAttributes)
    public class DetailArrayOfОценПричУвольн : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Popyt.DetailArrayOfОценПричУвольн members)

        // *** End programmer edit section *** (IIS.Popyt.DetailArrayOfОценПричУвольн members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОценПричУвольн by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОценПричУвольн.
        /// </summary>
        public DetailArrayOfОценПричУвольн(IIS.Popyt.Анкеты fАнкеты) : 
                base(typeof(ОценПричУвольн), ((ICSSoft.STORMNET.DataObject)(fАнкеты)))
        {
        }
        
        public IIS.Popyt.ОценПричУвольн this[int index]
        {
            get
            {
                return ((IIS.Popyt.ОценПричУвольн)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Popyt.ОценПричУвольн dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
