//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Popyt
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Стаж.
    /// </summary>
    // *** Start programmer edit section *** (Стаж CustomAttributes)

    // *** End programmer edit section *** (Стаж CustomAttributes)
    public enum Стаж
    {
        
        // *** Start programmer edit section *** (Стаж.ДоГода CustomAttributes)

        // *** End programmer edit section *** (Стаж.ДоГода CustomAttributes)
        ДоГода,
        
        // *** Start programmer edit section *** (Стаж.От1Года CustomAttributes)

        // *** End programmer edit section *** (Стаж.От1Года CustomAttributes)
        От1Года,
        
        // *** Start programmer edit section *** (Стаж.От3 CustomAttributes)

        // *** End programmer edit section *** (Стаж.От3 CustomAttributes)
        От3,
        
        // *** Start programmer edit section *** (Стаж.От5 CustomAttributes)

        // *** End programmer edit section *** (Стаж.От5 CustomAttributes)
        От5,
        
        // *** Start programmer edit section *** (Стаж.Более10 CustomAttributes)

        // *** End programmer edit section *** (Стаж.Более10 CustomAttributes)
        Более10,
    }
}
