//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Popyt
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Факторы.
    /// </summary>
    // *** Start programmer edit section *** (Факторы CustomAttributes)

    // *** End programmer edit section *** (Факторы CustomAttributes)
    public enum Факторы
    {
        
        // *** Start programmer edit section *** (Факторы.ВзаимСРуков CustomAttributes)

        // *** End programmer edit section *** (Факторы.ВзаимСРуков CustomAttributes)
        ВзаимСРуков,
        
        // *** Start programmer edit section *** (Факторы.ВзаимCКоллег CustomAttributes)

        // *** End programmer edit section *** (Факторы.ВзаимCКоллег CustomAttributes)
        ВзаимCКоллег,
        
        // *** Start programmer edit section *** (Факторы.СанитГигиеУсл CustomAttributes)

        // *** End programmer edit section *** (Факторы.СанитГигиеУсл CustomAttributes)
        СанитГигиеУсл,
        
        // *** Start programmer edit section *** (Факторы.СистЛьгот CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистЛьгот CustomAttributes)
        СистЛьгот,
        
        // *** Start programmer edit section *** (Факторы.СнабНеобхИнст CustomAttributes)

        // *** End programmer edit section *** (Факторы.СнабНеобхИнст CustomAttributes)
        СнабНеобхИнст,
        
        // *** Start programmer edit section *** (Факторы.СистОфицПриз CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистОфицПриз CustomAttributes)
        СистОфицПриз,
        
        // *** Start programmer edit section *** (Факторы.ИнтенРабот CustomAttributes)

        // *** End programmer edit section *** (Факторы.ИнтенРабот CustomAttributes)
        ИнтенРабот,
        
        // *** Start programmer edit section *** (Факторы.ИнфСотруд CustomAttributes)

        // *** End programmer edit section *** (Факторы.ИнфСотруд CustomAttributes)
        ИнфСотруд,
        
        // *** Start programmer edit section *** (Факторы.ПерспКарРоста CustomAttributes)

        // *** End programmer edit section *** (Факторы.ПерспКарРоста CustomAttributes)
        ПерспКарРоста,
        
        // *** Start programmer edit section *** (Факторы.СистОбучения CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистОбучения CustomAttributes)
        СистОбучения,
        
        // *** Start programmer edit section *** (Факторы.РазмЗарабПлат CustomAttributes)

        // *** End programmer edit section *** (Факторы.РазмЗарабПлат CustomAttributes)
        РазмЗарабПлат,
        
        // *** Start programmer edit section *** (Факторы.СистАдаптации CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистАдаптации CustomAttributes)
        СистАдаптации,
        
        // *** Start programmer edit section *** (Факторы.СистПремир CustomAttributes)

        // *** End programmer edit section *** (Факторы.СистПремир CustomAttributes)
        СистПремир,
        
        // *** Start programmer edit section *** (Факторы.СодерРаботы CustomAttributes)

        // *** End programmer edit section *** (Факторы.СодерРаботы CustomAttributes)
        СодерРаботы,
        
        // *** Start programmer edit section *** (Факторы.РезулРаботы CustomAttributes)

        // *** End programmer edit section *** (Факторы.РезулРаботы CustomAttributes)
        РезулРаботы,
        
        // *** Start programmer edit section *** (Факторы.ОргРабПроцес CustomAttributes)

        // *** End programmer edit section *** (Факторы.ОргРабПроцес CustomAttributes)
        ОргРабПроцес,
        
        // *** Start programmer edit section *** (Факторы.Престижность CustomAttributes)

        // *** End programmer edit section *** (Факторы.Престижность CustomAttributes)
        Престижность,
    }
}
